"""Tests for the reachables visualizer (rich console + mermaid + HTML).

The java-petclinic fixtures were generated by invoking the latest atom
(``atom reachables -l java``) on the spring-petclinic corpus and cdxgen for
the companion SBOM, so they exercise the shapes the tools emit today -
including the bare-array chunk format.
"""

from atom_tools.lib.visualizer import (
    VisualizationModel,
    component_licenses,
    load_bom,
    mm_escape,
    mm_label,
    render_console,
    render_html,
    render_mermaid,
)
from atom_tools.lib.reachables import load_reachables

PETCLINIC = "test/data/java-petclinic-reachables.json"
PETCLINIC_BOM = "test/data/java-petclinic-bom.json"
ATOM_TOOLS = "test/data/py-atom-tools-reachables.json"
ATOM_TOOLS_BOM = "test/data/py-atom-tools-bom.json"


def _model(fixture=PETCLINIC, bom=None):
    entries = load_reachables(fixture).get("reachables", [])
    return VisualizationModel.build(entries, load_bom(bom) if bom else None)


def test_model_from_latest_atom_fixture():
    model = _model()
    # The latest atom writes bare arrays; the loader wraps them transparently.
    assert len(model.flows) == 163
    assert model.purl_counts
    assert "framework-input" in model.tags
    # petclinic carries PII tags on its flows.
    assert any(t.startswith("pii") for t in model.tags)
    assert model.files
    assert model.tagged_flows > 0


def test_model_with_cdxgen_sbom():
    model = _model(bom=PETCLINIC_BOM)
    assert len(model.bom_components) == 237
    # All 8 reachable purls appear in the cdxgen SBOM (with ?type=jar
    # qualifiers on both sides).
    assert model.reachable_components == len(model.purl_counts) == 8


def test_sbom_matching_tolerates_qualifiers(tmp_path):
    entries = [
        {
            "flows": [
                {
                    "parentFileName": "a.py",
                    "lineNumber": 1,
                    "name": "req",
                    "code": "req.args",
                    "tags": "framework-input",
                },
                {
                    "parentFileName": "a.py",
                    "lineNumber": 2,
                    "name": "cursor.execute",
                    "code": "cursor.execute(q)",
                    "tags": "sql",
                },
            ],
            "purls": ["pkg:pypi/flask@3.0.0"],
        }
    ]
    bom = {
        "components": [
            # Same purl without the qualifier atom might not add for pypi.
            {"name": "flask", "version": "3.0.0", "purl": "pkg:pypi/flask@3.0.0",
             "licenses": [{"license": {"id": "BSD-3-Clause"}}]},
        ]
    }
    model = VisualizationModel.build(entries, bom)
    assert model.reachable_components == 1
    component = model.bom_component_for("pkg:pypi/flask@3.0.0")
    assert component_licenses(component) == "BSD-3-Clause"
    # Qualifier on the reachables side still matches a bare SBOM purl.
    model2 = VisualizationModel.build(
        [{**entries[0], "purls": ["pkg:pypi/flask@3.0.0?vcs_url=..."]}], bom
    )
    assert model2.reachable_components == 1


def test_flow_info_risk_and_tags():
    entries = [
        {
            "flows": [
                {"parentFileName": "s.py", "lineNumber": 1, "name": "req",
                 "code": "req.args", "tags": "framework-input"},
                {"parentFileName": "d.py", "lineNumber": 9, "name": "execute",
                 "code": 'db.execute("...")', "tags": "sql"},
            ],
            "purls": [],
        }
    ]
    model = VisualizationModel.build(entries)
    flow = model.flows[0]
    assert flow.risk == "high"
    assert flow.primary_tag == "sql"
    assert flow.steps == 2
    assert flow.source_label() == "req:1"
    assert "execute" in flow.sink_label()


def test_mm_escape():
    assert '"' not in mm_escape('say "hi" [now] {here} |all| \\of it')
    assert mm_escape("line1\nline2") == "line1"
    assert mm_escape("clean label") == "clean label"
    # Labels are kept whole by default; long java paths and purls must survive.
    assert mm_escape("x" * 100) == "x" * 100
    # An explicit limit still truncates.
    assert len(mm_escape("x" * 100, 44)) <= 44


def test_mm_label_wraps_without_losing_text():
    purl = "pkg:maven/org.springframework/spring-context-support@7.0.8?type=jar"
    label = mm_label(purl, 30)
    assert "<br/>" in label
    assert "…" not in label
    # Every character survives the wrap; only <br/> separators are added.
    assert label.replace("<br/>", "") == purl
    # Wrapping is disabled with 0, and short labels are left alone.
    assert mm_label(purl, 0) == purl
    assert mm_label("short", 30) == "short"
    # A version is never split across lines.
    for line in mm_label(purl, 30).split("<br/>"):
        assert not line.endswith("7.")
        assert not line.endswith("0.")
    # Relative paths break on the path separator.
    path = "src/main/java/org/springframework/samples/petclinic/owner/Owner.java"
    assert mm_label(path, 30).replace("<br/>", "") == path
    assert all(seg.endswith("/") for seg in mm_label(path, 30).split("<br/>")[:-1])


def test_mermaid_keeps_full_paths_and_purls():
    model = _model(bom=PETCLINIC_BOM)
    diagram = render_mermaid(model, max_flows=25)
    assert "…" not in diagram
    # Full relative source path, not a basename or an elided prefix.
    assert "src/main/java/org/springframework/samples/petclinic" in diagram.replace("<br/>", "")
    # Full purl including scheme, namespace and version.
    assert "pkg:maven/org.springframework/" in diagram.replace("<br/>", "")


def test_mermaid_structure():
    model = _model(bom=PETCLINIC_BOM)
    diagram = render_mermaid(model, max_flows=25)
    lines = diagram.splitlines()
    assert lines[0] == "flowchart LR"
    assert "classDef source" in diagram
    assert "classDef sinkHigh" in diagram
    assert "classDef pkg" in diagram
    assert 'subgraph sg0["' in diagram
    # Every node is declared exactly once.
    declarations = [ln.strip() for ln in lines if ":::" in ln]
    assert declarations
    seen = set()
    for decl in declarations:
        ident = decl.split("(")[0].split("[")[0].split("{")[0]
        assert ident not in seen, f"node {ident} declared twice"
        seen.add(ident)
    # Edges and package links are present.
    assert "-->" in diagram
    assert "-.->" in diagram
    # Escaping: no raw backslashes or pipes survive in labels.
    assert "\\" not in diagram
    assert "|" not in diagram.replace("-->|", "").replace("| ", "")


def test_mermaid_max_flows_respected():
    model = _model()
    diagram = render_mermaid(model, max_flows=5)
    assert diagram.count("-->") <= 5 + 5  # flow edges only within cap


def test_mermaid_high_risk_nodes_use_subroutine_shape():
    entries = [
        {
            "flows": [
                {"parentFileName": "s.py", "lineNumber": 1, "name": "req",
                 "code": "req.url", "tags": ""},
                {"parentFileName": "d.py", "lineNumber": 2, "name": "get",
                 "code": "requests.get(url)", "tags": "ssrf"},
            ],
            "purls": [],
        }
    ]
    diagram = render_mermaid(VisualizationModel.build(entries), 10)
    assert '[["' in diagram  # subroutine shape for high risk sinks
    assert ':::sinkHigh' in diagram
    assert 'ssrf' in diagram


def test_html_document():
    model = _model(bom=PETCLINIC_BOM)
    diagram = render_mermaid(model, 10)
    document = render_html(model, diagram, PETCLINIC)
    assert "mermaid" in document
    assert "flowchart LR" in document
    assert "Reachable data flows" in document
    # The mermaid source is html-escaped for safe embedding.
    assert "class=" not in diagram or diagram.replace("<", "&lt;") in document
    assert "SBOM components reachable" in document
    # Default rendering loads mermaid from the CDN.
    assert "cdn.jsdelivr.net/npm/mermaid" in document


def test_html_embeds_mermaid_for_offline_use():
    model = _model()
    diagram = render_mermaid(model, 5)
    payload = 'var mermaid = {}; "</script><b>evil</b>"'
    document = render_html(model, diagram, PETCLINIC, mermaid_js=payload)
    # The renderer is inlined and the CDN is not referenced.
    assert "cdn.jsdelivr.net" not in document
    assert payload.replace("</script", "<\\/script") in document
    # The escaped sequence cannot terminate the script element.
    assert "</script><b>evil</b>" not in document.split("</head>")[0]


def test_console_render_captures_report():
    model = _model(bom=PETCLINIC_BOM)
    console = render_console(model)
    text = console.export_text()
    assert "Reachables overview" in text
    assert "Data flows by file" in text
    assert "Reachable packages" in text
    assert "Proven reachable" in text
    assert "Apache-2.0" in text


def test_python_fixture_from_latest_atom():
    model = _model(ATOM_TOOLS, ATOM_TOOLS_BOM)
    assert len(model.flows) == 215
    # The python frontend does not resolve package purls onto flows.
    assert not model.purl_counts
    assert model.tagged_flows > 0
    diagram = render_mermaid(model, 10)
    assert diagram.startswith("flowchart LR")


def test_empty_model_renders():
    model = VisualizationModel.build([])
    assert model.flows == []
    assert render_mermaid(model).strip() != ""
    assert "Flow groups" in render_console(model).export_text()
