repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [ python ]
      - id: end-of-file-fixer
        types: [ python ]
      - id: check-docstring-first
        types: [ python ]
#      - id: double-quote-string-fixer
#        types: [ python ]

#  - repo: https://github.com/psf/black
#    rev: 23.11.0
#    hooks:
#      - id: black

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        exclude: 'cli'
        args: []

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: 'cli'
        args: [--statistics]

ci:
  autofix_prs: false
