name: OS matrix CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'pre-commit.yml'
      - 'release.yml'
      - 'test.yml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Make sure versions are synced if PR or ref is tag
      if: ${{ github.event_name == 'pull_request' || github.ref_type == 'tag' }}
      shell: bash
      run: |
        init_version=$(head -n 4 atom_tools/__init__.py | tail -1 | cut -d"'" -f2)
        toml_version=$(head -n 3 pyproject.toml | tail -1 | cut -d'"' -f2)
        if [ "$init_version" != "$toml_version" ]; then
          echo "Version in atom_tools.__init__.py does not match pyproject.toml."
          exit 1
        else
          echo "Version in atom_tools.__init__.py matches pyproject.toml."
        fi
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install .[dev]
    - name: Tox
      run: |
        python3 -m tox
        coverage run -m pytest test
        coverage report